Groupease/groupease

- CONTRIBUTING.md
- README.md
* Creates CONTRIBUTING.md to explain the rules and workflow for code changes.
* Adds a "Creating Issues" section with a link and instructions.
* Adds a "Committing Code" section that explains the Issue requirement and commit messages rules.
* Adds a "Submitting Pull Requests" section to explain the git workflow, forks, and pull-requests.
* Adds a Contributing section to README.md that links to the new CONTRIBUTING.md.
* Adds Waffle.io counts to README.md.
* Adds building and running instructions to README.md.
* Closes #1.
> Issue #1: Collaboration Rules Needed

- .gitignore
- .travis.yml
* Adds Travis CI YAML file to configure CI build.
* Adds IntelliJ iml files to gitignore.
* Closes #6.
> Issue #6: Travis CI

- .gitignore
- .travis.yml
- groupease-server/src/main/java/io/github/groupease/channel/Channel.java
- groupease-server/src/main/java/io/github/groupease/channel/MockChannelDao.java
This was built on top of Issue #6 so that the CI would auto-build the pull-request, so the diff contains its changes too.
The Channel object changes are for Issue #9.
> Issue 9 fix channel builder

- groupease-client/src/app/app.module.ts
- groupease-client/src/app/auth/auth.service.spec.ts
- groupease-client/src/app/auth/auth.service.ts
- groupease-client/src/app/user.service.spec.ts
- groupease-client/src/app/user.service.ts
- groupease-client/src/app/user.ts
- groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
- groupease-server/src/main/java/io/github/groupease/user/JpaUserDao.java
* Adds User class client-side.
* Adds UserService client-side.
* Saves user data into DB on sign in.
* Fixes issues with DAOs where objects may not refresh.
* Closes #33
> Issue #33: Client Save User

- groupease-server/src/main/java/io/github/groupease/channel/ChannelDao.java
- groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
- groupease-server/src/main/java/io/github/groupease/channel/ChannelWebService.java
- groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
- groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
- groupease-server/src/main/java/io/github/groupease/channel/MockChannelDao.java
- groupease-server/src/test/java/io/github/groupease/channel/ChannelWebServiceTest.java
* Adds a query param for userId to filter channels
> Issue #16: List all channels for a channel member

- groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.html
- groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.scss
- groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.spec.ts
- groupease-client/src/app/channel-directory/channel-creator/channel-creator.component.ts
- groupease-client/src/app/channel-directory/channel-directory-routing.module.ts
- groupease-client/src/app/channel-directory/channel-directory.module.ts
- groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.html
- groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.spec.ts
* Adds FAB to channel-directory to create new channel.
* Adds channel-creator component to channel-directory module.
* Adds form to channel-creator component.
* Creates channel with channel service.
* Navigates to new channel home on creation.
* Shows snackbar message on creation success or failure.
Closes #40
> Issue #40: Create Channel UI

- groupease-client/src/app/channel-admin/channel-admin.module.ts
- groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.html
- groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.scss
- groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.spec.ts
- groupease-client/src/app/channel-admin/join-request-list/join-request-list.component.ts
- groupease-client/src/app/channel-directory/channel-directory.module.ts
- groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.html
- groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.scss
- groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.spec.ts
- groupease-client/src/app/channel-directory/channel-directory/channel-directory.component.ts
- groupease-client/src/app/core/channel-join-request.service.spec.ts
- groupease-client/src/app/core/channel-join-request.service.ts
- groupease-client/src/app/core/channel-join-request.ts
- groupease-client/src/app/core/core.module.ts
- groupease-server/src/main/java/io/github/groupease/model/ChannelJoinRequest.java
- groupease-server/src/main/java/io/github/groupease/restendpoint/ChannelJoinRequestService.java
- groupease-server/src/main/java/io/github/groupease/util/CommentWrapper.java
* Adds channel-join-request service.
* Adds ability to create join requests on channel directory.
* Adds server annotation to ignore unknown JSON properties.
* Removes server ignore annotation on ChannelJoinRequest.channel.
* Adds ability for admins to approve join requests.
Closes #43
> Issue #43: Channel Join Request UI

- groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
Adds an additional overload for "create" method of MemberDao takes IDs instead of objects
> Additional "create" overload

- groupease-client/src/app/channel-admin/user-list/user-list.component.html
- groupease-client/src/app/channel-admin/user-list/user-list.component.scss
- groupease-client/src/app/channel-admin/user-list/user-list.component.spec.ts
- groupease-client/src/app/channel-admin/user-list/user-list.component.ts
- groupease-client/src/app/core/channel-invitation.service.spec.ts
- groupease-client/src/app/core/channel-invitation.service.ts
- groupease-client/src/app/core/channel-invitation.ts
- groupease-client/src/app/core/core.module.ts
- groupease-client/src/app/dashboard/dashboard.module.ts
- groupease-client/src/app/dashboard/invitation-list/invitation-list.component.html
- groupease-client/src/app/dashboard/invitation-list/invitation-list.component.scss
- groupease-client/src/app/dashboard/invitation-list/invitation-list.component.spec.ts
- groupease-client/src/app/dashboard/invitation-list/invitation-list.component.ts
- groupease-server/src/main/java/io/github/groupease/model/ChannelInvitation.java
- groupease-server/src/main/java/io/github/groupease/util/ChannelInvitationCreateWrapper.java
* Adds channel invitation service.
* Adds channel invitation class.
* Adds annotations to server objects to ignore unknown fields.
* Implements list of users in admin invitations tab.
* Implements ability to send invitation.
* Implements list of invitations in a user's dashboard.
* Implements ability for user to approve or reject invitations.
Closes #46
> Issue #46: Channel Invitation UI

- groupease-server/src/main/java/io/github/groupease/channel/ChannelEditByNonOwnerException.java
- groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
- groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
- groupease-server/src/main/java/io/github/groupease/model/Member.java
- groupease-server/src/test/java/io/github/groupease/GroupeaseTestGuiceModule.java
- groupease-server/src/test/java/io/github/groupease/channel/DefaultChannelServiceTest.java
* Adds current user as member and owner when creating a channel.
* Ensures channel edits and deletes can only be done by channel owner.
Closes #41
> Issue #41: New Channel Owner

- groupease-client/src/app/channel-group/channel-group-directory/channel-group-directory.component.html
- groupease-client/src/app/channel-group/channel-group-routing.module.ts
- groupease-client/src/app/channel-group/channel-group.module.ts
- groupease-client/src/app/channel-group/group-details-home/group-details-home.component.html
- groupease-client/src/app/channel-group/group-details-home/group-details-home.component.spec.ts
- groupease-client/src/app/channel-group/group-details-home/group-details-home.component.ts
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.html
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.spec.ts
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.ts
- groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.html
- groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.spec.ts
- groupease-client/src/app/channel-group/group-details-requests/group-details-requests.component.ts
- groupease-client/src/app/channel-group/group-details/group-details.component.html
- groupease-client/src/app/channel-group/group-details/group-details.component.ts
- groupease-client/src/app/channel-group/group-member-list/group-member-list.component.html
- groupease-client/src/app/channel-group/group-member-list/group-member-list.component.scss
- groupease-client/src/app/channel-group/group-member-list/group-member-list.component.spec.ts
- groupease-client/src/app/channel-group/group-member-list/group-member-list.component.ts
- groupease-client/src/app/channel-group/group-summary/group-summary.component.html
- groupease-client/src/app/channel-group/group-summary/group-summary.component.scss
- groupease-client/src/app/channel-group/group-summary/group-summary.component.spec.ts
- groupease-client/src/app/channel-group/group-summary/group-summary.component.ts
- groupease-server/src/main/java/io/github/groupease/model/GroupeaseUser.java
* Implements group summary card on details page.
* Adds placeholder routes for group join requests and invitations.
* Implements group member list as expansion panels.
* Fixes property names in the duplicate server GroupeaseUser class.
Closes #54
> Issue #54: Group Details

- groupease-client/src/app/app.component.html
- groupease-client/src/app/app.component.scss
- groupease-client/src/app/home/home.module.ts
- groupease-client/src/app/home/home/home.component.html
- groupease-client/src/app/home/home/home.component.scss
- groupease-client/src/app/home/home/home.component.spec.ts
- groupease-client/src/app/home/home/home.component.ts
- groupease-client/src/groupease-theme.scss
- groupease-client/src/material-theme-config.scss
- groupease-client/src/styles.scss
* Implements a marketing-style home page.
* Fixes the app toolbar on top of all views.
Closes #61
> Issue #61: Home Page

- db/migration/V1__Initial_Schema.sql
- groupease-client/src/app/core/core.module.ts
- groupease-client/src/app/core/member.service.spec.ts
- groupease-client/src/app/core/member.service.ts
- groupease-client/src/app/core/member.ts
- groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
- groupease-server/src/main/java/io/github/groupease/channel/ChannelWebService.java
- groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
- groupease-server/src/main/java/io/github/groupease/channel/JpaChannelDao.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberDeleteForbiddenException.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberGuiceModule.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberIdMismatchException.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberNotFoundException.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberService.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberWebService.java
- groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java
- groupease-server/src/main/java/io/github/groupease/config/guice/GroupeaseGuiceModule.java
- groupease-server/src/main/java/io/github/groupease/db/ChannelJoinRequestDao.java
- groupease-server/src/main/java/io/github/groupease/db/GroupDao.java
- groupease-server/src/main/java/io/github/groupease/db/GroupeaseUserDao.java
- groupease-server/src/main/java/io/github/groupease/db/MemberDao.java
- groupease-server/src/main/java/io/github/groupease/model/Channel.java
- groupease-server/src/main/java/io/github/groupease/model/Member.java
- groupease-server/src/main/java/io/github/groupease/restendpoint/GroupInvitationService.java
- groupease-server/src/main/java/io/github/groupease/restendpoint/GroupWebService.java
- groupease-server/src/main/java/io/github/groupease/user/DefaultUserService.java
- groupease-server/src/main/java/io/github/groupease/user/JpaUserDao.java
- groupease-server/src/main/java/io/github/groupease/user/UserWebService.java
- groupease-server/src/test/java/io/github/groupease/channel/DefaultChannelServiceTest.java
* Creates skeleton for channel member API using existing Member and DAO.
* Adds fields to member object and table.
* Adds member service client-side.
* Adds fields to member class client-side.
* Fixes update by exposing channel on JSON.
Closes #25
> Issue #25: Channel Member API

- groupease-client/src/app/channel-group/group-member-list/group-member-list.component.html
- groupease-client/src/app/channel-profile/channel-profile-routing.module.ts
- groupease-client/src/app/channel-profile/channel-profile.module.ts
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.html
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.spec.ts
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.ts
- groupease-client/src/app/channel-profile/profile-form/profile-form.component.html
- groupease-client/src/app/channel-profile/profile-form/profile-form.component.scss
- groupease-client/src/app/channel-profile/profile-form/profile-form.component.spec.ts
- groupease-client/src/app/channel-profile/profile-form/profile-form.component.ts
- groupease-client/src/app/channel-profile/profile-home/profile-home.component.html
- groupease-client/src/app/channel-profile/profile-home/profile-home.component.scss
- groupease-client/src/app/channel-profile/profile-home/profile-home.component.spec.ts
- groupease-client/src/app/channel-profile/profile-home/profile-home.component.ts
- groupease-client/src/app/channel/channel-navigation/channel-navigation.component.html
- groupease-client/src/app/channel/channel-routing.module.ts
* Adds Profile page to channel and navigation.
* Allows editing the current user's member profile.
* Shows new member fields in group members list.
Closes #57
> Issue #57: Edit Member Profile

- groupease-client/src/app/channel-group/group-details-home/group-details-home.component.ts
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.html
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.scss
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.spec.ts
- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.ts
- groupease-client/src/app/core/core.module.ts
- groupease-client/src/app/core/group-invitation.service.spec.ts
- groupease-client/src/app/core/group-invitation.service.ts
- groupease-client/src/app/core/group-invitation.ts
* Implements creating group invitation functionality.
Closes #59
> Issue #59: Group Invitation

- groupease-client/src/app/channel-group/group-details-invitations/group-details-invitations.component.ts
- groupease-client/src/app/channel-profile/channel-profile.module.ts
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.html
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.scss
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.spec.ts
- groupease-client/src/app/channel-profile/member-invitations/member-invitations.component.ts
- groupease-client/src/app/core/group-invitation.service.ts
- groupease-client/src/app/core/group-invitation.ts
* Allows a user to accept or reject a group invitation.
Closes #60
> Issue #60: Group Invitation Response

- groupease-server/src/main/java/io/github/groupease/channel/ChannelService.java
- groupease-server/src/main/java/io/github/groupease/channel/DefaultChannelService.java
- groupease-server/src/main/java/io/github/groupease/channelmember/ChannelMemberNotOwnerException.java
- groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java
Checking to make sure user is authorized to make changes
Deleting Channel if no more channelMembers remain
> Issue #69 & Issue #70

- groupease-client/src/app/channel-admin/member-list/member-list.component.html
- groupease-client/src/app/channel-admin/member-list/member-list.component.scss
- groupease-client/src/app/channel-admin/member-list/member-list.component.spec.ts
- groupease-client/src/app/channel-admin/member-list/member-list.component.ts
* Adds list of all channel members to admin tab.
* Allows channel owners to demote channel owners.
* Allows channel owners to promote channel members to owners.
* Allows channel owners to delete members from the channel.
Closes #73
> Issue #73: Admin Channel Members

- groupease-server/src/main/webapp/loaderio-16e2f61c7a51dfebd94f965fd0e81f98.txt
* Adds loaderio verification file in webapp root.
Closes #91
> Issue-91: Loaderio Support

- groupease-server/src/main/java/io/github/groupease/channelmember/DefaultChannelMemberService.java
- groupease-server/src/main/java/io/github/groupease/channelmember/MemberEditForbiddenException.java
* Fixes bugs with member saving validation.
Closes #101
> Issue #101: Non-owner Cannot Save Profile Bug
